name: Learning GitHub Scripting

on:
  issues:
    types: [opened]
    
jobs:
  comment-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on the new issue
        uses: actions/github-script@0.8.0
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment ({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🎉 Your issue has been automatically commented!!!"
            })
            
      - name: Add issue to project board
        if: contains(github.event.issue.labels.*.name, 'bug')
        uses: actions/github-script@0.8.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.projects.createCard({
              column_id: 18959632,
              content_id: context.payload.issue.id,
              content_type: "Issue"
            });
